language: objective-c
osx_image: xcode8
script:
  - cd Examples
  - xcodebuild -version
  - xcodebuild -project DynamicFontExample.xcodeproj -scheme iosTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios
